require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Metrics/ParameterLists:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    NSAStorage: nsastorage
